#!/usr/bin/env bash

source ~/repos/newin/.local/bin/functions/req.txt

# Define color codes
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
W='\033[33m'
BL='\033[36m'
RD='\033[01;31m'
BGN='\033[4;92m'
GN='\033[1;92m'
DGN='\033[32m'
CL='\033[m'
CM="${GN}✓${CL}"
CROSS="${RD}✗${CL}"
BFR="\\r\\033[K"
NC='\033[0m' # No Color
red="$( (/usr/bin/tput bold || :; /usr/bin/tput setaf 1 || :) 2>&-)"
plain="$( (/usr/bin/tput sgr0 || :) 2>&-)"


available()
 {
   command -v $* &>/dev/null; #&& echo "$* is installed" || echo "$* is NOT installed"
 }

status()
  {
   echo ">>> $*" >&2
  }

error()
  {
   echo "${red}ERROR: $*${plain}"
  }

warning()
  {
   echo "${red}$@${plain}"
  }

test_success()
  {
   status 'This is a test. Only a test...'
  }

require()
  {
    local MISSING=''
    for TOOL in $*; do
        if ! available $TOOL; then
            MISSING="$MISSING $TOOL"
        fi
    done

    echo $MISSING
  }

NEEDS=$(require ${debian_apps[@]})


if [ -n "$NEEDS" ]; then
    warning "ERROR: The following tools are required but missing: ${NEEDS}"
    for NEED in $NEEDS; do
        error "  - $NEED"
    done
fi

exit 223

